#!/bin/bash
# MiracleCast GUI Desktop Integration Script
# Author: Generated by Claude
# License: GNU-LGPL (same as MiracleCast)

# Create the script to launch the GUI with pkexec
cat > /tmp/miraclecast-gui-launcher.sh << 'EOF'
#!/bin/bash
# Launcher for MiracleCast GUI with proper permissions

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  # Re-run with pkexec
  pkexec "$0" "$@"
  exit $?
fi

# When running as root, launch the GUI
# Set display and xauthority for GUI to work as root
export DISPLAY=${DISPLAY:-:0}
export XAUTHORITY=${XAUTHORITY:-$HOME/.Xauthority}

# Run the GUI
python3 /usr/local/bin/miraclecast-gui.py
EOF

# Make the launcher executable
chmod +x /tmp/miraclecast-gui-launcher.sh

# Create desktop entry
cat > /tmp/miraclecast.desktop << EOF
[Desktop Entry]
Name=MiracleCast GUI
Comment=GUI for MiracleCast WiFi Display tools
Exec=/usr/local/bin/miraclecast-gui-launcher.sh
Icon=network-wireless
Terminal=false
Type=Application
Categories=Network;Utility;
Keywords=miracast;wifi;display;
EOF

# Ask for sudo permission to install
echo "Installing MiracleCast GUI (requires sudo)..."

# Copy files to their locations
sudo mkdir -p /usr/local/bin
sudo cp /tmp/miraclecast-gui-launcher.sh /usr/local/bin/miraclecast-gui-launcher.sh
sudo cp miraclecast-gui.py /usr/local/bin/miraclecast-gui.py

# Install desktop entry
sudo cp /tmp/miraclecast.desktop /usr/share/applications/

# Clean up temporary files
rm /tmp/miraclecast-gui-launcher.sh /tmp/miraclecast.desktop

# Create PolicyKit file to allow running as root without password prompt each time
sudo tee /usr/share/polkit-1/actions/org.miraclecast.gui.policy > /dev/null << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <vendor>MiracleCast</vendor>
  <vendor_url>https://github.com/albfan/miraclecast</vendor_url>
  <action id="org.miraclecast.gui">
    <description>Run MiracleCast WiFi Display GUI</description>
    <message>Authentication is required to run MiracleCast GUI</message>
    <icon_name>network-wireless</icon_name>
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/local/bin/miraclecast-gui-launcher.sh</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
  </action>
</policyconfig>
EOF

echo "MiracleCast GUI has been installed successfully!"
echo "You can now launch it from your application menu or run 'sudo miraclecast-gui.py'"